"""add recharges table

Revision ID: 3ef97263c33e
Revises: ea1f616263f1
Create Date: 2026-05-22 13:14:01.009037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef97263c33e'
down_revision: Union[str, Sequence[str], None] = 'ea1f616263f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recharges',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=False),
    sa.Column('operator', sa.Enum('airtel', 'jio', 'vi', 'bsnl', 'tataplay', 'dishtv', name='rechargeoperator'), nullable=False),
    sa.Column('recharge_type', sa.Enum('prepaid', 'dth', 'data_card', name='rechargetype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('plan_description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', 'refunded', name='rechargestatus'), nullable=False),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('operator_ref', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recharges_id'), 'recharges', ['id'], unique=False)
    op.create_index(op.f('ix_recharges_reference_id'), 'recharges', ['reference_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recharges_reference_id'), table_name='recharges')
    op.drop_index(op.f('ix_recharges_id'), table_name='recharges')
    op.drop_table('recharges')
    # ### end Alembic commands ###
