"""add bill payments table

Revision ID: ea1f616263f1
Revises: 1cbf7dd385c0
Create Date: 2026-05-22 12:27:53.105501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea1f616263f1'
down_revision: Union[str, Sequence[str], None] = '1cbf7dd385c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_payments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('electricity', 'water', 'gas', 'dth', 'broadband', 'mobile_postpaid', 'insurance', 'loan_emi', name='billcategory'), nullable=False),
    sa.Column('biller_name', sa.String(length=255), nullable=False),
    sa.Column('consumer_number', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', name='billpaymentstatus'), nullable=False),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('operator_ref', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_payments_id'), 'bill_payments', ['id'], unique=False)
    op.create_index(op.f('ix_bill_payments_reference_id'), 'bill_payments', ['reference_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bill_payments_reference_id'), table_name='bill_payments')
    op.drop_index(op.f('ix_bill_payments_id'), table_name='bill_payments')
    op.drop_table('bill_payments')
    # ### end Alembic commands ###
