"""add payment links table

Revision ID: ed2d5141d4ba
Revises: be9fae90815f
Create Date: 2026-05-21 15:26:08.433171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed2d5141d4ba'
down_revision: Union[str, Sequence[str], None] = 'be9fae90815f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_links',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_fixed_amount', sa.Boolean(), nullable=False),
    sa.Column('link_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('active', 'paid', 'expired', 'cancelled', name='paymentlinkstatus'), nullable=False),
    sa.Column('max_payments', sa.String(length=10), nullable=True),
    sa.Column('total_collected', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_links_id'), 'payment_links', ['id'], unique=False)
    op.create_index(op.f('ix_payment_links_link_code'), 'payment_links', ['link_code'], unique=True)
    op.drop_constraint(op.f('kyc_user_id_key'), 'kyc', type_='unique')
    op.drop_index(op.f('ix_kyc_user_id'), table_name='kyc')
    op.create_index(op.f('ix_kyc_user_id'), 'kyc', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kyc_user_id'), table_name='kyc')
    op.create_index(op.f('ix_kyc_user_id'), 'kyc', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('kyc_user_id_key'), 'kyc', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_payment_links_link_code'), table_name='payment_links')
    op.drop_index(op.f('ix_payment_links_id'), table_name='payment_links')
    op.drop_table('payment_links')
    # ### end Alembic commands ###
